name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install pnpm
        run: npm install -g pnpm@9.14.2

      - name: Check pnpm version
        run: pnpm -v

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: zip create
        run: zip -qq -r build.zip build/
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp build.zip s3://toucheese-team4-s3/build.zip

      - name: Verify S3 Upload
        run: aws s3 ls s3://toucheese-team4-s3/

      - name: Deploy
        run: |
          aws deploy create-deployment \
            --application-name TOUCHEESE-TEAM4 \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name TOUCHEESE-TEAM4-Deploy-Group \
            --s3-location bucket=toucheese-team4-s3,bundleType=zip,key=build.zip
